/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** crawl a website gathering all links to array */
export function collectAllLinks(n: string): Promise<Website>
export class Website {
  /** all of the website links. */
  links: Array<string>
}
